version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            sudo pip install -r requirements.txt
            python -m tests.unit_tests
            
      - run:
          name: deploy to heroku
          command: |
            git push https://heroku:$e07f70f1-87a1-4fdb-9c15-e27654818bc0@git.heroku.com/$frozen-crag-41604.git master
          
          